---
title: "Research Compendium Deliverable"
author: "A J Vijlbrief"
format: html
editor: visual
---

## Introduction

------------------------------------------------------------------------

This document is part of the research compendium deliverable for the MLARPIS course of MSBBSS 2025/2026. I will be creating a reproducible file for [this](https://wwwn.cdc.gov/nchs/nhanes/continuousnhanes/default.aspx?Begi-nYear=2015) project by the CDC. The data relevant to this specific study was taken from [here](https://github.com/mlarpis/markup/tree/main/documents/week-4/raw_data) and should be the same data as in this research compendium.

## Simulation study

------------------------------------------------------------------------

We begin by loading all the required packages.

```{r}
#| label: Loading packages
#| file: scripts/0.packages.R
#| warning: false

```

Secondly, we import the data. The files should be in the same place, the compendium, as this project file.

```{r}
#| label: Importing data
#| file: scripts/1.data.import.R
#| warning: false
#| message: false

```

We will then transform the data and perform initial descriptive analyses.

```{r}
#| label: Transforming data
#| warning: false
#| file: scripts/2.data.transform.R



```

Continued by the simulation.

```{r}
#| label: Simulating 
#| file: scripts/3.simulation.R
#| warning: false
#| output: false


```

And finally, we will display the results graphically.

```{r}
#| label: Creating figures
#| file: scripts/4.figures.R
#| echo: false
#| warning: false



```
